import * as XLSX from 'xlsx';
import { ContractHeader, DefectRecord, ContractSegment } from '../types';

export const SAMPLE_CONTRACTS: ContractSegment[] = [
  {
    id: 'CTR-001',
    numeroContrato: 'SR-400/2023',
    empresa: 'CONSTRUTORA TRIANGULO RODOVIAS S.A.',
    supervisora: 'CONSÓRCIO SUPERVISOR DNIT-SUL',
    kmInicial: 0.0,
    kmFinal: 10.0,
    rodovia: 'BR-101/SC',
    trecho: 'Trecho 01 - Div. PR/SC ao Km 10',
  },
  {
    id: 'CTR-002',
    numeroContrato: 'SR-401/2023',
    empresa: 'PAVIMENTADORA SUL LTDA',
    supervisora: 'CONSÓRCIO SUPERVISOR DNIT-SUL',
    kmInicial: 10.0,
    kmFinal: 20.0,
    rodovia: 'BR-101/SC',
    trecho: 'Trecho 02 - Km 10 ao Km 20 (Entr. BR-470)',
  },
];

export const SAMPLE_HEADER: ContractHeader = {
  contrato: '00 00418/2024 - CREMA BR-101/SC',
  rodovia: 'BR-101/SC',
  trecho: 'Div. PR/SC (Km 0,00) - Entr. BR-470 (Navegantes, Km 112,50)',
  kmInicialGlobal: 0.0,
  kmFinalGlobal: 20.0,
  extensaoTotalKm: 20.0,
  empresa: 'CONSTRUTORA TRIANGULO RODOVIAS S.A.',
  supervisora: 'CONSÓRCIO SUPERVISOR DNIT-SUL',
  dataLevantamento: '15/07/2026',
  snv: '101BSC0010',
  uf: 'SC',
  lote: 'LOTE 01',
};

export const SAMPLE_DEFECTS_PAVED: DefectRecord[] = [
  {
    id: 'DEF-P01',
    rodovia: 'BR-101/SC',
    trecho: 'Trecho Pavimentado Lote 01',
    kmInicial: 0.20,
    kmFinal: 0.50,
    lado: 'E',
    faixa: 'Faixa 1',
    tipoDefeito: 'Panela',
    gravidade: 'Alta',
    extensaoM: 300,
    observacoes: 'Panela profunda no revestimento asfáltico',
  },
  {
    id: 'DEF-P02',
    rodovia: 'BR-101/SC',
    trecho: 'Trecho Pavimentado Lote 01',
    kmInicial: 0.80,
    kmFinal: 1.20,
    lado: 'D',
    faixa: 'Faixa 1',
    tipoDefeito: 'Remendo',
    gravidade: 'Média',
    extensaoM: 400,
    observacoes: 'Remendo profundo com desnível de bordo',
  },
  {
    id: 'DEF-P03',
    rodovia: 'BR-101/SC',
    trecho: 'Trecho Pavimentado Lote 01',
    kmInicial: 1.50,
    kmFinal: 2.10,
    lado: 'E',
    faixa: 'Faixa 2',
    tipoDefeito: 'Trincamento',
    gravidade: 'Alta',
    extensaoM: 600,
    observacoes: 'Trincamento tipo couro de jacaré com erosão local',
  },
  {
    id: 'DEF-P04',
    rodovia: 'BR-101/SC',
    trecho: 'Trecho Pavimentado Lote 01',
    kmInicial: 2.50,
    kmFinal: 3.20,
    lado: 'E',
    faixa: 'Faixa 1',
    tipoDefeito: 'Roçada',
    gravidade: 'Baixa',
    extensaoM: 700,
    observacoes: 'Necessidade de roçada na faixa de domínio',
  },
  {
    id: 'DEF-P05',
    rodovia: 'BR-101/SC',
    trecho: 'Trecho Pavimentado Lote 01',
    kmInicial: 3.50,
    kmFinal: 4.00,
    lado: 'D',
    faixa: 'Faixa 1',
    tipoDefeito: 'Drenagem',
    gravidade: 'Média',
    extensaoM: 500,
    observacoes: 'Bueiro obstructed por sedimento',
  },
  {
    id: 'DEF-P06',
    rodovia: 'BR-101/SC',
    trecho: 'Trecho Pavimentado Lote 01',
    kmInicial: 4.20,
    kmFinal: 4.80,
    lado: 'D',
    faixa: 'Faixa 1',
    tipoDefeito: 'Sinalização Vertical',
    gravidade: 'Alta',
    extensaoM: 600,
    observacoes: 'Placas Danificadas/ausentes no trecho',
  },
  {
    id: 'DEF-P07',
    rodovia: 'BR-101/SC',
    trecho: 'Trecho Pavimentado Lote 01',
    kmInicial: 5.10,
    kmFinal: 5.80,
    lado: 'E',
    faixa: 'Faixa 1',
    tipoDefeito: 'Sinalização Horizontal',
    gravidade: 'Péssima',
    extensaoM: 700,
    observacoes: 'Pintura de faixas apagada por desgaste severo',
  },
  {
    id: 'DEF-P08',
    rodovia: 'BR-101/SC',
    trecho: 'Trecho Pavimentado Lote 02',
    kmInicial: 10.50,
    kmFinal: 11.20,
    lado: 'D',
    faixa: 'Faixa 1',
    tipoDefeito: 'Panela',
    gravidade: 'Péssima',
    extensaoM: 700,
    observacoes: 'Sequência de panelas críticas no trecho contratual SR-401/2023',
  },
  {
    id: 'DEF-P09',
    rodovia: 'BR-101/SC',
    trecho: 'Trecho Pavimentado Lote 02',
    kmInicial: 12.00,
    kmFinal: 12.80,
    lado: 'E',
    faixa: 'Faixa 1',
    tipoDefeito: 'Trincamento',
    gravidade: 'Média',
    extensaoM: 800,
    observacoes: 'Fissuração longitudinal no centro da faixa',
  },
  {
    id: 'DEF-P10',
    rodovia: 'BR-101/SC',
    trecho: 'Trecho Pavimentado Lote 02',
    kmInicial: 14.20,
    kmFinal: 15.00,
    lado: 'D',
    faixa: 'Faixa 1',
    tipoDefeito: 'Sinalização Horizontal',
    gravidade: 'Alta',
    extensaoM: 800,
    observacoes: 'Falta de tachões refletivos e demarcação',
  },
];

export const SAMPLE_DEFECTS: DefectRecord[] = [
  {
    id: 'DEF-001',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 0.20,
    kmFinal: 0.45,
    lado: 'D',
    faixa: 'Faixa 1',
    tipoDefeito: 'Panelas',
    gravidade: 'Baixa',
    extensaoM: 250,
    estacaInicial: 10,
    estacaFinal: 22.5,
    observacoes: 'Pequenas panelas isoladas no acostamento',
  },
  {
    id: 'DEF-002',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 0.80,
    kmFinal: 1.30,
    lado: 'E',
    faixa: 'Faixa 2',
    tipoDefeito: 'Trilha de Roda',
    gravidade: 'Média',
    extensaoM: 500,
    estacaInicial: 40,
    estacaFinal: 65,
    observacoes: 'Afundamento médio no trilho de roda externo',
  },
  {
    id: 'DEF-003',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 1.10,
    kmFinal: 1.40,
    lado: 'D',
    faixa: 'Faixa 1',
    tipoDefeito: "Poças D'água",
    gravidade: 'Alta',
    extensaoM: 300,
    estacaInicial: 55,
    estacaFinal: 70,
    observacoes: 'Acúmulo de água na pista decorrente de deficiência no greide',
  },
  {
    id: 'DEF-004',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 1.50,
    kmFinal: 1.90,
    lado: 'D',
    faixa: 'Faixa 1',
    tipoDefeito: 'Drenagem',
    gravidade: 'Baixa',
    extensaoM: 400,
    estacaInicial: 75,
    estacaFinal: 95,
    observacoes: 'Sarjeta obstruída por vegetação e assoreamento',
  },

  // Km 2 - 5
  {
    id: 'DEF-005',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 2.10,
    kmFinal: 2.50,
    lado: 'E',
    faixa: 'Faixa 1',
    tipoDefeito: 'Excesso de Poeira',
    gravidade: 'Média',
    extensaoM: 400,
    estacaInicial: 105,
    estacaFinal: 125,
    observacoes: 'Acúmulo excessivo de fina poeira e material solto no acostamento',
  },
  {
    id: 'DEF-006',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 2.60,
    kmFinal: 2.90,
    lado: 'E',
    faixa: 'Faixa 1',
    tipoDefeito: 'Corrugações',
    gravidade: 'Alta',
    extensaoM: 300,
    estacaInicial: 130,
    estacaFinal: 145,
    observacoes: 'Deformação plástica ondulada acentuada na área de frenagem',
  },
  {
    id: 'DEF-007',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 3.10,
    kmFinal: 3.60,
    lado: 'D',
    faixa: 'Faixa 1',
    tipoDefeito: 'Excesso de Bordo',
    gravidade: 'Média',
    extensaoM: 500,
    estacaInicial: 155,
    estacaFinal: 180,
    observacoes: 'Degrau entre pista de rolamento e acostamento > 4cm',
  },
  {
    id: 'DEF-008',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 4.00,
    kmFinal: 4.25,
    lado: 'D',
    faixa: 'Faixa 1',
    tipoDefeito: 'Panelas',
    gravidade: 'Péssima',
    extensaoM: 250,
    estacaInicial: 200,
    estacaFinal: 212.5,
    observacoes: 'Múltiplas panelas severas com risco iminente de colisão',
  },

  // Km 5 - 10
  {
    id: 'DEF-009',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 5.20,
    kmFinal: 5.90,
    lado: 'E',
    faixa: 'Faixa 2',
    tipoDefeito: 'Trincamento',
    gravidade: 'Média',
    extensaoM: 700,
    estacaInicial: 260,
    estacaFinal: 295,
    observacoes: 'Mapeamento de trincas do tipo couro de jacaré sem erosão',
  },
  {
    id: 'DEF-010',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 6.10,
    kmFinal: 6.40,
    lado: 'D',
    faixa: 'Faixa 1',
    tipoDefeito: 'Seção Trans. Impropria',
    gravidade: 'Alta',
    extensaoM: 300,
    estacaInicial: 305,
    estacaFinal: 320,
    observacoes: 'Inversão desfavorável de superelevação em curva',
  },
  {
    id: 'DEF-011',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 7.00,
    kmFinal: 7.70,
    lado: 'E',
    faixa: 'Faixa 1',
    tipoDefeito: 'Remendos',
    gravidade: 'Baixa',
    extensaoM: 700,
    estacaInicial: 350,
    estacaFinal: 385,
    observacoes: 'Remendos superficiais antigos com leve turgidez',
  },
  {
    id: 'DEF-012',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 8.30,
    kmFinal: 8.90,
    lado: 'D',
    faixa: 'Faixa 1',
    tipoDefeito: 'Drenagem',
    gravidade: 'Péssima',
    extensaoM: 600,
    estacaInicial: 415,
    estacaFinal: 445,
    observacoes: 'Bueiro de greide colapsado necessitando reconstituição urgente',
  },
  {
    id: 'DEF-013',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 9.20,
    kmFinal: 9.80,
    lado: 'E',
    faixa: 'Faixa 1',
    tipoDefeito: "Poças D'água",
    gravidade: 'Média',
    extensaoM: 600,
    estacaInicial: 460,
    estacaFinal: 490,
    observacoes: 'Lâmina de água acumulada em período de chuva contínua',
  },

  // Km 10 - 15
  {
    id: 'DEF-014',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 10.10,
    kmFinal: 10.60,
    lado: 'D',
    faixa: 'Faixa 1',
    tipoDefeito: 'Trilha de Roda',
    gravidade: 'Alta',
    extensaoM: 500,
    estacaInicial: 505,
    estacaFinal: 530,
    observacoes: 'Afundamento severo > 20mm com retenção hídrica',
  },
  {
    id: 'DEF-015',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 11.20,
    kmFinal: 11.50,
    lado: 'E',
    faixa: 'Faixa 1',
    tipoDefeito: 'Panelas',
    gravidade: 'Alta',
    extensaoM: 300,
    estacaInicial: 560,
    estacaFinal: 575,
    observacoes: 'Desagregação profunda do CBUQ em rampa ascendente',
  },
  {
    id: 'DEF-016',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 12.10,
    kmFinal: 12.70,
    lado: 'D/E',
    faixa: 'Ambos',
    tipoDefeito: 'Excesso de Poeira',
    gravidade: 'Péssima',
    extensaoM: 600,
    estacaInicial: 605,
    estacaFinal: 635,
    observacoes: 'Poeira densa resultante de obra não asperada reduzindo visibilidade',
  },
  {
    id: 'DEF-017',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 13.40,
    kmFinal: 13.90,
    lado: 'E',
    faixa: 'Faixa 2',
    tipoDefeito: 'Corrugações',
    gravidade: 'Média',
    extensaoM: 500,
    estacaInicial: 670,
    estacaFinal: 695,
    observacoes: 'Ondulações transversais provocadas por tráfego pesado',
  },
  {
    id: 'DEF-018',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 14.20,
    kmFinal: 14.70,
    lado: 'D',
    faixa: 'Faixa 1',
    tipoDefeito: 'Excesso de Bordo',
    gravidade: 'Péssima',
    extensaoM: 500,
    estacaInicial: 710,
    estacaFinal: 735,
    observacoes: 'Degrau crítico com desmoronamento de bordo da pista',
  },

  // Km 15 - 20
  {
    id: 'DEF-019',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 15.10,
    kmFinal: 15.50,
    lado: 'E',
    faixa: 'Faixa 1',
    tipoDefeito: "Poças D'água",
    gravidade: 'Baixa',
    extensaoM: 400,
    estacaInicial: 755,
    estacaFinal: 775,
    observacoes: 'Poça localizada no acostamento esquerdo',
  },
  {
    id: 'DEF-020',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 16.30,
    kmFinal: 16.90,
    lado: 'D',
    faixa: 'Faixa 1',
    tipoDefeito: 'Drenagem',
    gravidade: 'Média',
    extensaoM: 600,
    estacaInicial: 815,
    estacaFinal: 845,
    observacoes: 'Valetas de proteção de aterro obstruídas',
  },
  {
    id: 'DEF-021',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 17.50,
    kmFinal: 18.20,
    lado: 'E',
    faixa: 'Faixa 1',
    tipoDefeito: 'Trilha de Roda',
    gravidade: 'Péssima',
    extensaoM: 700,
    estacaInicial: 875,
    estacaFinal: 910,
    observacoes: 'Afundamento plástico contínuo de alta severidade com trincas',
  },
  {
    id: 'DEF-022',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 18.60,
    kmFinal: 19.10,
    lado: 'D',
    faixa: 'Faixa 1',
    tipoDefeito: 'Panelas',
    gravidade: 'Média',
    extensaoM: 500,
    estacaInicial: 930,
    estacaFinal: 955,
    observacoes: 'Múltiplas cavas de pequena dimensão no centro da faixa',
  },
  {
    id: 'DEF-023',
    rodovia: 'BR-101/SC',
    trecho: 'Lote 01',
    kmInicial: 19.40,
    kmFinal: 19.90,
    lado: 'E',
    faixa: 'Faixa 1',
    tipoDefeito: 'Seção Trans. Impropria',
    gravidade: 'Alta',
    extensaoM: 500,
    estacaInicial: 970,
    estacaFinal: 995,
    observacoes: 'Aplanamento do bombeamento central da pista',
  },
];

/**
 * Creates and downloads a real .xlsx file matching the ICMWeb export standard.
 */
export function generateSampleXLSXBlob(): Blob {
  const wb = XLSX.utils.book_new();

  // Header metadata rows
  const headerData = [
    ['SISTEMA ICMWeb - RELATÓRIO DE LEVANTAMENTO DE DEFEITOS RODOVIÁRIOS'],
    ['CONTRATO:', SAMPLE_HEADER.contrato, '', 'RODOVIA:', SAMPLE_HEADER.rodovia],
    ['TRECHO:', SAMPLE_HEADER.trecho, '', 'SNV:', SAMPLE_HEADER.snv],
    ['EMPRESA:', SAMPLE_HEADER.empresa, '', 'SUPERVISORA:', SAMPLE_HEADER.supervisora],
    ['DATA LEVANTAMENTO:', SAMPLE_HEADER.dataLevantamento, '', 'UF:', SAMPLE_HEADER.uf],
    [], // empty row separator
    [
      'RODOVIA',
      'TRECHO',
      'KM INICIAL',
      'KM FINAL',
      'ESTACA INICIAL',
      'ESTACA FINAL',
      'LADO',
      'FAIXA',
      'TIPO DE DEFEITO',
      'GRAVIDADE',
      'EXTENSÃO (M)',
      'OBSERVAÇÕES',
    ],
  ];

  // Defect data rows
  const defectRows = SAMPLE_DEFECTS.map((d) => [
    d.rodovia,
    d.trecho,
    d.kmInicial,
    d.kmFinal,
    d.estacaInicial ?? d.kmInicial * 50,
    d.estacaFinal ?? d.kmFinal * 50,
    d.lado,
    d.faixa ?? 'Faixa 1',
    d.tipoDefeito,
    d.gravidade,
    d.extensaoM,
    d.observacoes ?? '',
  ]);

  const fullData = [...headerData, ...defectRows];

  const ws = XLSX.utils.aoa_to_sheet(fullData);

  // Auto-fit column widths
  ws['!cols'] = [
    { wch: 12 }, // Rodovia
    { wch: 15 }, // Trecho
    { wch: 12 }, // Km Inicial
    { wch: 12 }, // Km Final
    { wch: 14 }, // Estaca Inicial
    { wch: 14 }, // Estaca Final
    { wch: 8 },  // Lado
    { wch: 10 }, // Faixa
    { wch: 30 }, // Tipo Defeito
    { wch: 12 }, // Gravidade
    { wch: 14 }, // Extensao
    { wch: 45 }, // Observacoes
  ];

  XLSX.utils.book_append_sheet(wb, ws, 'ICMWeb_Levantamento');

  const arrayBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  return new Blob([arrayBuffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
}

export function createSampleConsistencyReport(): import('../types').ConsistencyReport {
  return {
    fileName: 'Modelo_Levantamento_ICMWeb_BR101.xlsx',
    fileValid: true,
    totalRows: 28,
    validRecords: 24,
    invalidRecords: 0,
    warningCount: 2,
    pathologiesCount: 8,
    pathologiesList: [
      'Corrugações',
      'Drenagem',
      'Excesso de Bordo',
      'Excesso de Poeira',
      'Panelas',
      "Poças D'água",
      'Seção Trans. Impropria',
      'Trilha de Roda',
    ],
    totalExtensionKm: 20.0,
    processingTimeMs: 14.2,
    overlapsCount: 0,
    issues: [
      {
        line: 14,
        column: 'KM Inicial / KM Final',
        value: '12.80 > 12.20',
        cause: 'KM Inicial cadastrado superior ao KM Final na fonte.',
        suggestion: 'Invertido e corrigido para KM 12.20 - 12.80 automaticamente.',
        severity: 'warning',
      },
      {
        line: 21,
        column: 'Severidade',
        value: 'G3 (3)',
        cause: 'Formato de severidade numérico encontrado.',
        suggestion: 'Mapeado para nível Média (Regular).',
        severity: 'warning',
      },
    ],
  };
}

export function downloadSampleXLSX(): void {
  const blob = generateSampleXLSXBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'Modelo_ICMWeb_Grafico_Linear.xlsx';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
